rails:
  threads: 3
  log_level: info
  mailer:
    from: Code0 <testmail@code0.tech>
    address: smtp.example.com
    port: 587
    domain: code0.tech
    username: testmail@code0.tech
    password: changeme
  web:
    port: 3000
    bind: # For example: tcp://0.0.0.0:3000
    force_ssl:
  grpc:
    host: '0.0.0.0:50051'
  db:
    host: localhost
    port: 5433
    username: sagittarius
    password: sagittarius
    pool_size: 4
    encryption:
      primary_key: YzaMv4bXYK84unYIQI4Ms4sV3ucbvWs0
      deterministic_key: jgTaxTqzM15ved1S8HdXrqrjfCfF5R0h
      key_derivation_salt: Z6zcLTgobXLYjXUslRsLMKxvXKq3j6DJ
  secret_key_base: MVMD6CtQwEWrQ28TdokQakbG2FG5abOn

application_setting_overrides: {}
